services:
  signoz-proxy:
    image: signoz-proxy
    container_name: signoz-proxy
    ports:
      - "9092:9092"
    networks:
      - signoz-net
    restart: unless-stopped
    environment:
      LOG_LEVEL: debug

networks:
  signoz-net:
    external: true
