services:
  signoz-proxy:
    image: juliuskoval/signoz-proxy:latest
    container_name: signoz-proxy
    ports:
      - "9092:9092"
    networks:
      - signoz-net
    restart: unless-stopped
networks:
  signoz-net:
    external: true
